### ISSUE TITLE
PHP error in plugin.php

### ISSUE THREAD

**Issue by ctrlbrk42** [chesterrush/yourls-Time-Limit-Link#1]
When trying to 'activate' the plug-in, I get this in the error log (server 500):

2017/02/02 12:35:24 [error] 15269#15269: *53985225 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/yourls/user/plugins/Time-Limit-Link/plugin.php on line 62" while reading response header from upstream, client: xx, server: xx, request: "GET /admin/plugins.php?action=activate&plugin=Time-Limit-Link&nonce=d43665ed6d HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "xx", referrer: "https://xx/admin/plugins.php"

PHP 5.4.45-0+deb7u6 (cli) (built: Dec 10 2016 16:03:16)
YOURLS 1.7.0

**Comment by ctrlbrk42** [comment]
Nevermind, I found the broken variable.  Code as provided on github doesn't compile.

**Comment by chesterrush** [comment]
Hi ctrlbrk42, I fix the issue, thank you for your feedback.
